### ISSUE TITLE
1.8.9 only and other questions?

### ISSUE THREAD

**Issue by karl-police** [Quantizr/DungeonRoomsMod#16]
I was told about this mod. So I looked at the GitHub.

It says 1.8.9. And this is where I ask myself questions. First of all, I am not experienced that much about creating mods for Minecraft. There's source code, yes. But what I wonder is the version it can be used on.

I've seen other mods, like used in mod packs like FTB and etc. which get updates for more than one Minecraft Version, so as example, the mod would have a separate version for 1.8.9 and 1.12.2. Not sure if there are mods that work on two version or more, where Minecraft hasn't changed much, like 1.16.2 and 1.16.3. But then I am not sure if the .jar gets build twice for that or if it is just handled by Forge.

So would this work on other versions too, like 1.12.2 or 1.16.5?

Second question, I see this mod has /room command listened down. Now, what if Hypixel would hypothetically adds a /room command to some game. What would happen? What if there's another mod with the same commands. How can the user change the name of the command, is that implemented? Like "prefix".

**Comment by karl-police** [comment]
Also, since there is source code anyways. I've tried putting the .jar on 1.12.2, it doesn't work. Not sure if it will work if you would modify the .jar changing whatever triggers the version check, to 1.12.2.

But is it possible to take the source code and just build for another version? Also how?

**Comment by cinqdtun** [comment]
It's not possible to upgrade mod in another version of Minecraft by just taking current code and compile it since Minecraft functions are not the same in newer version.
If you want to make this mod compatible with a another version you need to rewrite the code where the mod call forge functions or Minecraft functions.
Each version of Minecraft has it own functions.
To answer to your other question client take priority , so basically if hypixel add same command than a mod, he will always take priority . I think if two mods register the same command 1 would be ignored or the game can potentially crashed, command can be modified only in source code they have no others way to modify them and command are not handled like other message and implemented as a command.
I hope that can answer to your questions !

**Comment by yanickrochon** [comment]
Minecraft 1.8.9 cannot be installed anymore. This mod should be updated to at least 1.18.

**Comment by lj-dunphy** [comment]
Yes you can still install 1.8.9, i have attached a image on how to do it
![image](https://user-images.githubusercontent.com/87740926/205405380-3fd8b2c5-5200-44ff-a6fd-1f6baa410f14.png)

**Comment by yanickrochon** [comment]
@cold-carmel yes, I did all that, but selecting "release 1.8.9" fails for me, the installation files are not found for download.

**Comment by karl-police** [comment]
> Minecraft 1.8.9 cannot be installed anymore. This mod should be updated to at least 1.18.

Have you Dungeons played Hypixel on 1.18?

Try it and play regular Floor 7 a couple of times. At some point you will crash, this is present from 1.16+ and even 1.15.

On 1.15 the Chunks are entirely bugged, and you can't load in with a snapshot version.


However, on 1.12 that doesn't occur, but most mods are still on 1.8.9

not sure why yours is failing, maybe try temporarily changing DNS, make sure to try both IPv4 and IPv6. You can Google for Google's DNS.

**Comment by yanickrochon** [comment]
> not sure why yours is failing, maybe try temporarily changing DNS, make sure to try both IPv4 and IPv6. You can Google for Google's DNS.

Well, it finally installed and I managed to get it working, a few days ago. One major problem I now have, and it is pretty annoying, is on F3, the gardians become invisible once killed. So, when they respawn, I cannot hit them. I have a FOT, which I can use, but it's slow...!!! I managed to kill all 4, but it took at 15 minutes!
